[en]
languageCode = "en"
languageName = "EN"
weight = 1
title = "MetaX"

[en.params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo_inverted@0.25x.png"
  secondaryLogo = "img/logo@0.25x.png"
  description = "MetaX"


[en.author]
  name = "MetaX"
  image = "img/metax_avatar.jpg"
  headline = "Pioneer of Web3.0 Creator Economy"
  bio = "Pioneer of Web3.0 Creator Economy"
  links = [
    { x-twitter = "https://twitter.com/helloxai" },
    { github = "https://github.com/bigiod/" },
  ]

[zh-cn]
languageCode = "zh-cn"
languageName = "中文简体"
weight = 2
title = "MetaX"

[zh-cn.params]
  displayName = "中文简体"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo_inverted@0.25x.png"
  secondaryLogo = "img/logo@0.25x.png"
  description = "MetaX"


 [zh-cn.author]
  name = "MetaX"
  image = "img/metax_avatar.jpg"
  headline = "AI & Web3.0 产品经理 / 小红书AI博主 / 创业者"
  bio = "Pioneer of Web3.0 Creator Economy"
  links = [
    { email = "mailto:hktybcc@gmail.com" },
    { x-twitter = "https://x.com/MetaversePlus" },
    { linkedin = "https://www.linkedin.com/in/aizx/" },
    { rednote = "https://www.xiaohongshu.com/user/profile/59f87643db2e602e550c9714" },
    # { bilibili = "https://www.xiaohongshu.com/user/profile/59f87643db2e602e550c9714" },
    { wechat = "https://www.xiaohongshu.com/user/profile/59f87643db2e602e550c9714" },    
    # { youtube = "https://linkedin/aizx" },
    { github = "https://github.com/itey/" },
  ]