# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


[[main]]
name = "首页"
pageRef = "/"
weight = 10

[[main]]
name = "🔥DeepSeek"
pageRef = "columns/deepseek"
weight = 10

[[main]]
name = "知识分享"
pageRef = "posts"
weight = 20

[[main]]
name = "成长叙事"
pageRef = "timeline"
weight = 30

[[main]]
name = "学习专栏"
pageRef = "columns"
weight = 30


# [[main]]
# name = "📚知识库"
# url  = "https://metaxai.notion.site/knowledgebase"
# weight = 40

# [[main]]
# name = "🔠 Prompt提示词"
#  parent = "📚知识库"
#  url = ""
#  weight = 4010

# [[main]]
#  name = "🧰 AI工具箱"
#  parent = "📚知识库"
#  url = ""
#  weight = 4020

# [[main]]
#  name = "📚 我的书架"
#  parent = "📚知识库"
#   url = ""
#  weight = 4030

# [[main]]
#  name = "🗞️ RSS订阅源"
#  parent = "📚知识库"
#  url = ""
#  weight = 4040

# [[main]]
#  name = "🛠️ HTML > Markdown"
#  parent = "📚知识库"
#  url = "https://devtool.tech/html-md"
#  weight = 4050

[[main]]
name = "赞助支持"
pageRef = "reward"
weight = 60

# [[main]]
# name = "关于"
# pageRef = "about"
# weight = 100



# [[main]]
# identifier = "twitter"
# pre = "x-twitter"
# url = "https://x.com/MetaversePlus"
# weight = 200

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/bigiod/"
weight = 300



# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "赞助"
pageRef = "reward"
weight = 10

[[footer]]
name = "关于"
pageRef = "about"
weight = 100

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

