# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.




[[main]]
  name = "🔥DeepSeek"
  pageRef = "columns/deepseek"
  weight = 10

[[main]]
  name = "新手快速使用指南"
  parent = "🔥DeepSeek"
  pageRef = "columns/deepseek/deepseek-usage-guide"
  weight = 1010

[[main]]
  name = "DeepSeek提问技巧"
  parent = "🔥DeepSeek"
  pageRef = "columns/deepseek/deepseek-questioning-skills"
  weight = 1020

[[main]]
  name = "DeepSeek+内容创作"
  parent = "🔥DeepSeek"
  pageRef = "columns/deepseek/deepseek-content-creation"
  weight = 1030

[[main]]
  name = "DeepSeek+创意设计"
  parent = "🔥DeepSeek"
  pageRef = "columns/deepseek/deepseek-creative-design"
  weight = 1040

[[main]]
  name = "DeepSeek+办公效率"
  parent = "🔥DeepSeek"
  pageRef = "columns/deepseek/deepseek-office-efficiency"
  weight = 1050

[[main]]
  name = "DeepSeek资源汇总"
  parent = "🔥DeepSeek"
  pageRef = "columns/deepseek/deepseek-resource-hub"
  weight = 1060

[[main]]
name = "知识分享"
pageRef = "posts"
weight = 20

[[main]]
  name = "AI内容创作"
  parent = "知识分享"
  pageRef = "zmt"
  weight = 2010

[[main]]
  name = "提示词工程"
  parent = "知识分享"
  pageRef = "prompt"
  weight = 2020

[[main]]
  name = "自动化工作流"
  parent = "知识分享"
  pageRef = "aiflowwork"
  weight = 2030

[[main]]
  name = "RSS订阅源"
  parent = "知识分享"
  pageRef = "rss"
  weight = 2040

[[main]]
  name = "AI SEO"
  parent = "知识分享"
  pageRef = "prompt"
  weight = 2050

[[main]]
name = "学习专栏"
pageRef = "columns"
weight = 30

[[main]]
  name = "DeepSeek"
  parent = "学习专栏"
  pageRef = "columns/deepseek"
  weight = 3005


# [[main]]
#  name = "AI超级个体"
#  parent = "学习专栏"
#  pageRef = ""
# weight = 3010

[[main]]
  name = "一人企业"
  parent = "学习专栏"
  pageRef = "columns/one-person-bussiness/00-menu"
  weight = 3020

[[main]]
  name = "dWebsite"
  parent = "学习专栏"
  pageRef = "columns/ens-ipfs-dwebsite/101-overview"
  weight = 3030

[[main]]
  name = "Markdown"
  parent = "学习专栏"
  pageRef = "columns/markdown/1-mastering-markdown-for-productivity"
  weight = 3040

[[main]]
  name = "AI自动化赚钱"
  parent = "学习专栏"
  pageRef = "columns/ai-automated-earning/1-medium-make-money"
  weight = 3050

[[main]]
name = "📚知识库"
 url  = "https://metaxai.notion.site/knowledgebase"
weight = 40

[[main]]
  name = "🔠 Prompt提示词"
  parent = "📚知识库"
  url = ""
  weight = 4010

[[main]]
  name = "🧰 AI工具箱"
  parent = "📚知识库"
  url = ""
  weight = 4020

[[main]]
  name = "📚 我的书架"
  parent = "📚知识库"
   url = ""
  weight = 4030

[[main]]
  name = "🗞️ RSS订阅源"
  parent = "📚知识库"
   url = ""
  weight = 4040

[[main]]
  name = "🛠️ HTML > Markdown"
  parent = "📚知识库"
  url = "https://devtool.tech/html-md"
  weight = 4050

[[main]]
name = "赞助支持"
pageRef = "reward"
weight = 60

[[main]]
name = "关于"
pageRef = "about"
weight = 100



# [[main]]
# identifier = "twitter"
# pre = "x-twitter"
# url = "https://x.com/MetaversePlus"
# weight = 200

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/bigiod/"
weight = 300



# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "赞助"
pageRef = "reward"
weight = 10

[[footer]]
name = "关于"
pageRef = "about"
weight = 100

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

