# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


[[main]]
name = "About"
pageRef = "about"
weight = 10

[[main]]
name = "Blog"
pageRef = "posts"
weight = 20

[[main]]
name = "Project"
pageRef = "posts"
weight = 30

[[main]]
name = "Resume"
pageRef = "posts"
weight = 40

[[main]]
name = "Resume"
pageRef = "posts"
weight = 50

[[main]]
name = "Reward"
pageRef = "reward"
weight = 100

#[[main]]
#name = "登录"
#url = "https://8x.world?msopen=/member/sign_in"
#weight = 110



# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "Reward"
pageRef = "reward"
weight = 10

[[footer]]
name = "About"
pageRef = "about"
weight = 100

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

